# Generated by Django 5.2.3 on 2026-06-10 23:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ['ubicacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del objeto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado_conservacion', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('muy_malo', 'Muy malo')], default='bueno', max_length=50, verbose_name='Estado de conservación')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor estimado (USD)')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación (soft delete)')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('can_read', models.BooleanField(default=False, verbose_name='Puede leer')),
                ('can_write', models.BooleanField(default=False, verbose_name='Puede escribir')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Puede editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Puede eliminar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text="Rol o parentesco dentro del sistema (ej: 'Hijo', 'Socio', 'Encargado de galpón')", verbose_name='Descripción')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='inventario.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LibroRevista',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.objeto')),
                ('autor', models.CharField(blank=True, max_length=300, verbose_name='Autor')),
                ('edicion', models.CharField(blank=True, max_length=100, verbose_name='Edición')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('isbn_issn', models.CharField(blank=True, help_text='Código ISBN para libros o ISSN para revistas', max_length=30, verbose_name='ISBN / ISSN')),
            ],
            options={
                'verbose_name': 'Libro / Revista',
                'verbose_name_plural': 'Libros / Revistas',
            },
            bases=('inventario.objeto',),
        ),
        migrations.CreateModel(
            name='MuebleArte',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.objeto')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Material')),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largo (cm)')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho (cm)')),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alto (cm)')),
                ('artista_fabricante', models.CharField(blank=True, max_length=300, verbose_name='Artista / Fabricante')),
            ],
            options={
                'verbose_name': 'Mueble / Arte',
                'verbose_name_plural': 'Muebles / Obras de Arte',
            },
            bases=('inventario.objeto',),
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.objeto')),
                ('tamano', models.CharField(blank=True, help_text='Ej: S, M, L, XL, 38, 42, etc.', max_length=50, verbose_name='Tamaño / Talla')),
            ],
            options={
                'verbose_name': 'Ropa / Accesorio',
                'verbose_name_plural': 'Ropa / Accesorios',
            },
            bases=('inventario.objeto',),
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('objeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.objeto')),
                ('marca', models.CharField(blank=True, max_length=200, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=200, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie único del dispositivo', max_length=200, verbose_name='Número de serie')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Almacena especificaciones flexibles en formato JSON (RAM, almacenamiento, etc.)', verbose_name='Especificaciones técnicas (JSON)')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
            bases=('inventario.objeto',),
        ),
        migrations.AddField(
            model_name='objeto',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_beneficiario', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiario'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='contenedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='inventario.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='dueno_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_dueno', to=settings.AUTH_USER_MODEL, verbose_name='Dueño original'),
        ),
        migrations.CreateModel(
            name='FotoObjeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='fotos_objetos/%Y/%m/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción de la foto')),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar si esta es la imagen principal del objeto', verbose_name='Foto principal')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.objeto', verbose_name='Objeto')),
            ],
            options={
                'verbose_name': 'Foto del objeto',
                'verbose_name_plural': 'Fotos de objetos',
                'ordering': ['-es_principal', 'fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='objeto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='inventario.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenedores', to='inventario.ubicacion', verbose_name='Ubicación'),
        ),
    ]
