# Generated by Django 6.0.6 on 2026-06-11 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Imagen del código QR generado para este contenedor', null=True, upload_to='qrcodes/', verbose_name='Código QR'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='campos_pendientes',
            field=models.JSONField(blank=True, default=list, help_text='Lista de campos que la IA no pudo determinar y requiere input del usuario', verbose_name='Campos pendientes'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='estado_carga',
            field=models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto - requiere datos del usuario'), ('pendiente_ia', 'Pendiente de análisis por IA')], default='pendiente_ia', help_text='Indica si el objeto tiene todos los datos o falta información del usuario', max_length=20, verbose_name='Estado de carga'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='plataformas_publicadas',
            field=models.JSONField(blank=True, default=list, help_text="Lista de plataformas donde se ha publicado (ej: ['facebook', 'instagram', 'mercadolibre'])", verbose_name='Plataformas publicadas'),
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_minimo', models.PositiveIntegerField(default=1, help_text='Cantidad mínima antes de generar alerta', verbose_name='Nivel mínimo')),
                ('cantidad_actual', models.PositiveIntegerField(default=1, verbose_name='Cantidad actual')),
                ('activa', models.BooleanField(default=True, verbose_name='Alerta activa')),
                ('ultima_verificacion', models.DateTimeField(auto_now=True, verbose_name='Última verificación')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('objeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_stock', to='inventario.objeto', verbose_name='Objeto')),
            ],
            options={
                'verbose_name': 'Alerta de stock',
                'verbose_name_plural': 'Alertas de stock',
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor anterior (USD)')),
                ('valor_nuevo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor nuevo (USD)')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia (USD)')),
                ('porcentaje_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Porcentaje de cambio')),
                ('motivo', models.CharField(blank=True, help_text='Ej: Revalorización, Depreciación, Actualización por IA, etc.', max_length=200, verbose_name='Motivo del cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='inventario.objeto', verbose_name='Objeto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Historial de precio',
                'verbose_name_plural': 'Historial de precios',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
