# Generated by Django 6.0.6 on 2026-08-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tiene_clave_temporal',
            field=models.BooleanField(default=False, help_text="True si el usuario está usando una contraseña temporal (flujo 'Olvidó su contraseña'). El frontend fuerza la redirección a /perfil hasta que defina una clave nueva.", verbose_name='Tiene clave temporal'),
        ),
    ]
