# Generated by Django 5.2.3 on 2026-06-23 02:20

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estok',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Mi Inventario', max_length=200, verbose_name='Nombre del Estok')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Estok',
                'verbose_name_plural': 'Estoks',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_en_estok', models.CharField(
                    choices=[
                        ('admin', 'Admin'),
                        ('editor', 'Editor'),
                        ('visualizador', 'Visualizador'),
                    ],
                    default='visualizador',
                    max_length=20,
                    verbose_name='Rol en el Estok',
                )),
                ('invitacion_aceptada', models.BooleanField(default=True, verbose_name='Invitación aceptada')),
                ('fecha_union', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de unión')),
                ('estok', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='miembros',
                    to='inventario.estok',
                    verbose_name='Estok',
                )),
                ('usuario', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='membresias',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Usuario',
                )),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'unique_together': {('estok', 'usuario')},
            },
        ),
        # Agregar campo estok a Objeto
        migrations.AddField(
            model_name='objeto',
            name='estok',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='objetos',
                to='inventario.estok',
                verbose_name='Estok',
            ),
        ),
        # Agregar campo estok a Ubicacion
        migrations.AddField(
            model_name='ubicacion',
            name='estok',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ubicaciones',
                to='inventario.estok',
                verbose_name='Estok',
            ),
        ),
        # Agregar campo estok a Contenedor
        migrations.AddField(
            model_name='contenedor',
            name='estok',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contenedores',
                to='inventario.estok',
                verbose_name='Estok',
            ),
        ),
    ]
