# Generated by Django 6.0.6 on 2026-06-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_contenedor_qr_code_image_objeto_campos_pendientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='contenedores/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largo (cm)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ubicaciones/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largo (cm)'),
        ),
    ]
