# Generated by Django 6.0.6 on 2026-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_customuser_tiene_clave_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_count',
            field=models.IntegerField(default=0, help_text='Contador total de autenticaciones exitosas del usuario. Lo incrementa la señal user_logged_in (ver inventario/signals.py) en el login JWT y en el admin de Django. Control de adopción en lanzamiento.', verbose_name='Inicios de sesión'),
        ),
    ]
