# Generated by Django 6.0.6 on 2026-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_customuser_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='login_count',
            field=models.IntegerField(default=0, help_text='Contador de veces que el usuario cargó o conmutó a este Estok (sincronización de inquilinato activo vía /api/cambiar-estok-activo/). Control analítico de accesos por Estok conectado.', verbose_name='Accesos a este Estok'),
        ),
    ]
