# Generated by Django 6.0.6 on 2026-06-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_contenedor_alto_contenedor_ancho_contenedor_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librorevista',
            options={'verbose_name': 'Libro / Revista / Cómic', 'verbose_name_plural': 'Libros / Revistas / Cómics'},
        ),
        migrations.AddField(
            model_name='librorevista',
            name='editorial',
            field=models.CharField(blank=True, help_text='Ej: Planeta DeAgostini, DC Comics, Marvel', max_length=200, verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='librorevista',
            name='idioma',
            field=models.CharField(blank=True, help_text='Ej: Español, Inglés, Portugués', max_length=100, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='librorevista',
            name='nombre_serie',
            field=models.CharField(blank=True, help_text='Ej: Garfield, Batman, Los Simpsons', max_length=300, verbose_name='Nombre de la serie'),
        ),
        migrations.AddField(
            model_name='librorevista',
            name='numero_tomo',
            field=models.IntegerField(blank=True, help_text='Ej: 2, 15, 100', null=True, verbose_name='Número del tomo'),
        ),
        migrations.AddField(
            model_name='librorevista',
            name='titulo_tomo',
            field=models.CharField(blank=True, help_text='Ej: Se queda con la torta, El caballero oscuro', max_length=300, verbose_name='Título del tomo'),
        ),
    ]
