# Generated by Django 5.2.15 on 2026-06-23 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_librorevista_options_librorevista_editorial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estok',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Mi Inventario', max_length=200, verbose_name='Nombre del Estok')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Estok',
                'verbose_name_plural': 'Estoks',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.CreateModel(
            name='CodigoInvitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Formato: EST-XXXXXXXX', max_length=20, unique=True, verbose_name='Código de invitación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usos_maximos', models.PositiveIntegerField(default=0, verbose_name='Usos máximos (0 = sin límite)')),
                ('usos_actuales', models.PositiveIntegerField(default=0, verbose_name='Usos actuales')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_invitacion', to='inventario.role', verbose_name='Rol a asignar')),
                ('estok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_invitacion', to='inventario.estok', verbose_name='Estok')),
            ],
            options={
                'verbose_name': 'Código de invitación',
                'verbose_name_plural': 'Códigos de invitación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='ultimo_estok_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos', to='inventario.estok', verbose_name='Último Estok activo'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='estok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='inventario.estok', verbose_name='Estok'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='estok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='inventario.estok', verbose_name='Estok'),
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de unión')),
                ('estok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='inventario.estok', verbose_name='Estok')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias', to='inventario.role', verbose_name='Rol en el Estok')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'unique_together': {('usuario', 'estok')},
            },
        ),
    ]
