# Generated by Django 6.0.6 on 2026-08-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_membresia_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='parent_contenedor',
            field=models.ForeignKey(blank=True, help_text='Si está definido, este contenedor es un sub-contenedor jerárquico de otro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontenedores', to='inventario.contenedor', verbose_name='Contenedor padre'),
        ),
    ]
