# Generated by Django 6.0.6 on 2026-08-28 (manual: blindaje categorías de usuario)

from django.db import migrations, models


# =============================================================================
# Snapshot de las 11 categorías macro oficiales al momento de esta migración.
# DEBE coincidir con CATEGORIAS_OFICIALES en
# inventario/management/commands/cargar_categorias_meli.py (un solo origen).
# =============================================================================
IDS_OFICIALES = [
    "MLA1574",  # Muebles
    "MLA1798",  # Arte
    "MLA1367",  # Coleccionables
    "MLA1368",  # Antigüedades
    "MLA1592",  # Jardín
    "MLA1648",  # Computación
    "MLA1051",  # Electrónica
    "MLA1403",  # Cocina
    "MLA1577",  # Hogar
    "MLA1500",  # Herramientas
    "MLA1506",  # Materiales
]


def marcar_oficiales_como_sistema(apps, schema_editor):
    """Marca las categorías oficiales existentes como categorías del sistema.

    Las categorías creadas por usuarios (sin meli_category_id o con IDs no
    oficiales) quedan en es_sistema=False y por lo tanto BLINDADAS contra la
    limpieza destructiva del seeding `cargar_categorias_meli`.
    """
    Categoria = apps.get_model("inventario", "Categoria")
    Categoria.objects.filter(meli_category_id__in=IDS_OFICIALES).update(es_sistema=True)


def desmarcar(apps, schema_editor):
    Categoria = apps.get_model("inventario", "Categoria")
    Categoria.objects.filter(meli_category_id__in=IDS_OFICIALES).update(es_sistema=False)


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_contenedor_parent_contenedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="es_sistema",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True si es una de las 11 categorías macro oficiales de "
                    "Mercado Libre inyectadas por el sistema. Las categorías "
                    "creadas por usuarios son False y el seeding jamás las "
                    "elimina."
                ),
                verbose_name="Categoría del sistema",
            ),
        ),
        migrations.RunPython(marcar_oficiales_como_sistema, desmarcar),
    ]
