# Generated by Django 6.0.6 on 2026-06-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_estok_remove_customuser_role_codigoinvitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='material',
            field=models.CharField(blank=True, choices=[('madera', 'Madera'), ('metal', 'Metal'), ('plastico', 'Plastico'), ('vidrio', 'Vidrio'), ('tela', 'Tela'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='tipo_madera',
            field=models.CharField(blank=True, choices=[('pino', 'Pino'), ('roble', 'Roble'), ('nogal', 'Nogal'), ('cerezo', 'Cerezo'), ('haya', 'Haya'), ('caoba', 'Caoba'), ('mdf', 'MDF'), ('aglomerado', 'Aglomerado'), ('terciado', 'Terciado (Multicapa)'), ('otro', 'Otro')], help_text="Solo aplica si el material es 'Madera'", max_length=50, null=True, verbose_name='Tipo de Madera'),
        ),
    ]
