# Generated by Django 6.0.6 on 2026-08-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_categoria_es_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='parent_grid_col',
            field=models.PositiveIntegerField(blank=True, help_text='Coordenada relativa (columna, 1-based) del casillero de la grilla del contenedor padre donde reside este elemento.', null=True, verbose_name='Columna del casillero en el contenedor padre'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='parent_grid_row',
            field=models.PositiveIntegerField(blank=True, help_text='Coordenada relativa (fila, 1-based) del casillero de la grilla del contenedor padre donde reside este elemento.', null=True, verbose_name='Fila del casillero en el contenedor padre'),
        ),
        migrations.AddField(
            model_name='estok',
            name='tipo_layout',
            field=models.CharField(choices=[('CASA_2_PISOS', 'Casa de 2 pisos'), ('VISTA_PLANTA_UNICA', 'Vista planta única')], default='VISTA_PLANTA_UNICA', help_text='Define cómo se renderiza el mapa espacial del Estok (inquilino).', max_length=50, verbose_name='Tipo de layout del mapa espacial'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='parent_grid_col',
            field=models.PositiveIntegerField(blank=True, help_text='Coordenada relativa (columna, 1-based) del casillero de la grilla del contenedor donde reside este objeto.', null=True, verbose_name='Columna del casillero en el contenedor'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='parent_grid_row',
            field=models.PositiveIntegerField(blank=True, help_text='Coordenada relativa (fila, 1-based) del casillero de la grilla del contenedor donde reside este objeto.', null=True, verbose_name='Fila del casillero en el contenedor'),
        ),
    ]
