# Generated by Django 6.0.6 on 2026-07-01 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_locations_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLibreToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID de usuario ML')),
                ('expires_in', models.IntegerField(default=21600, verbose_name='Segundos hasta expiración')),
                ('scope', models.TextField(blank=True, verbose_name='Scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Token de MercadoLibre',
                'verbose_name_plural': 'Tokens de MercadoLibre',
            },
        ),
    ]
