# Generated by Django 6.0.6 on 2026-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_locations_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLibreToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Token de acceso')),
                ('refresh_token', models.TextField(verbose_name='Token de refresh')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_in', models.IntegerField(default=21600, verbose_name='Segundos hasta expirar')),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token de MercadoLibre',
                'verbose_name_plural': 'Tokens de MercadoLibre',
            },
        ),
    ]
