# Generated by Django 6.0.6 on 2026-08-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_contenedor_parent_grid_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='grid_columnas',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de columnas de la grilla interna de casilleros del contenedor (ej: 3 en un armario empotrado).', verbose_name='Columnas de la grilla interna'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='grid_filas',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de filas de la grilla interna de casilleros del contenedor (ej: 2 en un armario empotrado).', verbose_name='Filas de la grilla interna'),
        ),
        migrations.AddField(
            model_name='estok',
            name='grid_columnas',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de columnas de la grilla estilo Word del macro-Estok (por piso).', verbose_name='Columnas de la grilla del macro-Estok'),
        ),
        migrations.AddField(
            model_name='estok',
            name='grid_filas',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de filas de la grilla estilo Word del macro-Estok (por piso).', verbose_name='Filas de la grilla del macro-Estok'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='grid_colspan',
            field=models.PositiveIntegerField(default=1, help_text='Ancho variable del cuadrante en celdas de la grilla estilo Word.', verbose_name='Ancho en celdas (colspan)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='grid_rowspan',
            field=models.PositiveIntegerField(default=1, help_text='Alto variable del cuadrante en celdas de la grilla estilo Word.', verbose_name='Alto en celdas (rowspan)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='parent_grid_col',
            field=models.PositiveIntegerField(blank=True, help_text='Coordenada relativa (columna, 1-based) del cuadrante de la grilla del piso donde reside esta ubicación.', null=True, verbose_name='Columna en la grilla del piso'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='parent_grid_row',
            field=models.PositiveIntegerField(blank=True, help_text='Coordenada relativa (fila, 1-based) del cuadrante de la grilla del piso donde reside esta ubicación.', null=True, verbose_name='Fila en la grilla del piso'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='piso',
            field=models.CharField(choices=[('PRIMER_PISO', '1er piso'), ('PLANTA_BAJA', 'Planta baja')], default='PLANTA_BAJA', help_text='Piso del macro-Estok donde se diagrama esta ubicación.', max_length=20, verbose_name='Piso de la casa'),
        ),
    ]
