# Generated by Django 6.0.6 on 2026-08-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_contenedor_grid_columnas_contenedor_grid_filas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='grid_filas_config',
            field=models.JSONField(blank=True, help_text='Arreglo opcional con la cantidad de casilleros de cada fila (ej: [3,2,2]). Si es null, todas las filas usan grid_columnas. Permite layouts asimétricos (Fila 1 de 3 celdas, Fila 2 de 2 celdas).', null=True, verbose_name='Columnas por fila (grilla asimétrica)'),
        ),
    ]
