# Generated by Django 6.0.6 on 2026-09-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_contenedor_grid_filas_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='grid_columnas',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de columnas por defecto de cada fila interna.', verbose_name='Columnas internas de la división'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='grid_filas',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de filas internas de la sub-grilla de la división.', verbose_name='Filas internas de la división'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='grid_filas_config',
            field=models.JSONField(blank=True, help_text='Arreglo opcional con las columnas de cada fila interna (ej: [3,2,2]). Si es null, todas usan grid_columnas.', null=True, verbose_name='Columnas por fila interna (grilla asimétrica)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='parent_ubicacion',
            field=models.ForeignKey(blank=True, help_text='División del Mapa Estok donde se encastra esta habitación (parent_id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sububicaciones', to='inventario.ubicacion', verbose_name='División padre'),
        ),
    ]
