# Generated by Django 6.0.6 on 2026-09-01 (manual, wizard del Mapa de Estok)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_ubicacion_grid_columnas_ubicacion_grid_filas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estok',
            name='grid_filas_config',
            field=models.JSONField(blank=True, help_text='Arreglo opcional con las columnas de cada fila del macro-plano (ej: [3,2]). Si es null, todas las filas usan grid_columnas.', null=True, verbose_name='Columnas por fila del macro-plano (grilla asimétrica)'),
        ),
    ]
