# Generated by Django 6.0.6 on 2026-07-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_mensajes_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alias_por_estok',
            field=models.JSONField(blank=True, default=dict, help_text="Dict con {estok_id: 'alias'} para mostrar nombres diferentes según el Estok", verbose_name='Alias por Estok'),
        ),
    ]
