# Generated by Django 6.0.6 on 2026-07-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_add_alias_por_estok'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, help_text='Timestamp del último ping/heartbeat del usuario', null=True, verbose_name='Última actividad'),
        ),
    ]
