# Generated by Django 6.0.6 on 2026-09-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_estok_grid_filas_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='es_inmueble',
            field=models.BooleanField(default=False, help_text='Si está activo, el mueble queda FIJO e inmóvil (mueble inmueble fijo): no puede arrastrarse ni eliminarse desde la pantalla de almacenamiento.', verbose_name='Mueble inmueble'),
        ),
    ]
