# Generated by Django 6.0.6 on 2026-09-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_contenedor_es_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='posicion_puerta',
            field=models.CharField(blank=True, choices=[('TOP', 'Superior'), ('BOTTOM', 'Inferior'), ('LEFT', 'Izquierda'), ('RIGHT', 'Derecha')], help_text='Pared de la habitación donde se colocó la puerta arrastrable (valores: TOP, BOTTOM, LEFT, RIGHT).', max_length=10, null=True, verbose_name='Posición de la puerta'),
        ),
    ]
