# Generated by Django 6.0.6 on 2026-07-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_add_ultima_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='privacidad',
            field=models.CharField(choices=[('compartido', 'Compartido'), ('privado', 'Privado')], default='compartido', help_text="'compartido' = visible para el usuario, 'privado' = oculto (uso interno)", max_length=20, verbose_name='Privacidad de la membresía'),
        ),
    ]
