# Generated by Django 6.0.6 on 2026-09-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_ubicacion_posicion_puerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='ui_height',
            field=models.CharField(blank=True, default='auto', help_text="Medida de alto relativo de la tarjeta en el lienzo interactivo (ej: 'auto' o '160px'). Se persiste en caliente vía PUT desde el resizing recursivo (Visor de Habitación / Contenedor Grande).", max_length=20, null=True, verbose_name='Alto visual (UI)'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ui_width',
            field=models.CharField(blank=True, default='100%', help_text="Medida de ancho relativo de la tarjeta en el lienzo interactivo (ej: '100%' o '210px'). Se persiste en caliente vía PUT desde el resizing recursivo (Visor de Habitación / Contenedor Grande).", max_length=20, null=True, verbose_name='Ancho visual (UI)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ui_height',
            field=models.CharField(blank=True, default='auto', help_text="Medida de alto relativo de la tarjeta en el lienzo interactivo (ej: 'auto' o '160px'). Se persiste en caliente vía PUT desde el resizing del Mapa Estok.", max_length=20, null=True, verbose_name='Alto visual (UI)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ui_width',
            field=models.CharField(blank=True, default='100%', help_text="Medida de ancho relativo de la tarjeta en el lienzo interactivo (ej: '100%' o '210px'). Se persiste en caliente vía PUT desde el resizing del Mapa Estok.", max_length=20, null=True, verbose_name='Ancho visual (UI)'),
        ),
    ]
