# Generated by Django 6.0.6 on 2026-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_add_privacidad_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='owner_action',
            field=models.CharField(blank=True, choices=[('vender', 'Vender'), ('recuperar', 'Recuperar'), ('tirar', 'Tirar / Desechar')], help_text='Decisión del dueño original sobre qué hacer con el objeto: Vender, Recuperar o Tirar', max_length=20, null=True, verbose_name='Acción del dueño original'),
        ),
    ]
