# Generated by Django 6.0.6 on 2026-07-15 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_add_owner_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='es_contenedor',
            field=models.BooleanField(default=False, help_text='Si está marcado, este objeto puede contener otros objetos dentro', verbose_name='Es contenedor'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='objeto_padre',
            field=models.ForeignKey(blank=True, help_text='Si este objeto está dentro de otro objeto que actúa como contenedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_contenidos', to='inventario.objeto', verbose_name='Objeto contenedor padre'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='owner_action',
            field=models.CharField(blank=True, choices=[('vender', 'Vender'), ('conservar', 'Conservar'), ('tirar', 'Tirar / Desechar')], help_text='Decisión del dueño original sobre qué hacer con el objeto: Vender, Conservar o Tirar', max_length=20, null=True, verbose_name='Acción del dueño original'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='inventario.estok', verbose_name='Estok')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'estok')},
            },
        ),
        migrations.AddField(
            model_name='objeto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='inventario.categoria', verbose_name='Categoría'),
        ),
    ]
