# Generated by Django 6.0.6 on 2026-09-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_contenedor_ui_height_contenedor_ui_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='espacio_lleno',
            field=models.BooleanField(default=False, help_text='Marca manual del casillero/estante del mueble (multi-elemento): si está activo, el espacio se pinta con opacidad sutil y deja de aceptar elementos por arrastre (dragover/ondrop bloqueados) hasta desmarcarlo. Se persiste vía PUT hermético al Estok activo.', verbose_name='Espacio físicamente lleno'),
        ),
    ]
