# Generated by Django 6.0.6 on 2026-09-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_contenedor_espacio_lleno'),
    ]

    operations = [
        migrations.AddField(
            model_name='estok',
            name='cantidad_pisos',
            field=models.PositiveIntegerField(default=1, help_text='Pregunta inicial obligatoria del alta de Estok: si es mayor a 1 se activa el Modo Casa (casa con techo puntiagudo y layout multi-planta); si es exactamente 1 se activa el Modo Planta Única (departamento de perímetro continuo, sin techo).', verbose_name='Cantidad de plantas (pisos) del inmueble'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='fusion_grupo',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID relacional compartido por dos o más espacios fusionados (ej: pasillos en L). Los espacios con el mismo fusion_grupo se renderizan como UN único espacio receptor Drag & Drop de geometría irregular, sin fronteras internas.', null=True, verbose_name='Grupo de fusión (espacio en L)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ui_left',
            field=models.CharField(blank=True, default='0%', help_text="Coordenada horizontal elástica del rectángulo libre dentro del contenedor del departamento (Modo Planta Única), ej: '12%'. Se persiste en caliente vía PUT desde el arrastre libre.", max_length=20, null=True, verbose_name='Posición X visual (UI)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ui_top',
            field=models.CharField(blank=True, default='0%', help_text="Coordenada vertical elástica del rectángulo libre dentro del contenedor del departamento (Modo Planta Única), ej: '8%'. Se persiste en caliente vía PUT desde el arrastre libre.", max_length=20, null=True, verbose_name='Posición Y visual (UI)'),
        ),
    ]
