# Generated by Django 6.0.6 on 2026-07-27 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_agregar_categoria_y_contenedor_inteligente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLibreToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Token de acceso')),
                ('refresh_token', models.TextField(verbose_name='Token de refresh')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_in', models.IntegerField(default=21600, verbose_name='Segundos hasta expirar')),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('ml_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='User ID de ML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercadolibre_token', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de MercadoLibre',
                'verbose_name_plural': 'Tokens de MercadoLibre',
            },
        ),
    ]
