# Generated by Django 6.0.6 on 2026-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_mercadolibretoken_multiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolibretoken',
            name='scope',
            field=models.TextField(blank=True, verbose_name='Scopes autorizados'),
        ),
    ]
