# Generated by Django 6.0.6 on 2026-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_inferir_cantidad_pisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='fusion_grupo',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID relacional compartido por dos o más muebles/estantes fusionados (geometría en L). Los espacios con el mismo fusion_grupo se renderizan como UN único rectángulo elástico receptor, sin fronteras internas.', null=True, verbose_name='Grupo de fusión (espacio en L)'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ui_left',
            field=models.CharField(blank=True, default='0%', help_text="Coordenada horizontal elástica del rectángulo libre dentro del lienzo del visor (Nivel 2 habitación / Nivel 3-4 interior del mueble), ej: '12%'. Se persiste en caliente vía PUT desde el arrastre libre.", max_length=20, null=True, verbose_name='Posición X visual (UI)'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ui_top',
            field=models.CharField(blank=True, default='0%', help_text="Coordenada vertical elástica del rectángulo libre dentro del lienzo del visor (Nivel 2 habitación / Nivel 3-4 interior del mueble), ej: '8%'. Se persiste en caliente vía PUT desde el arrastre libre.", max_length=20, null=True, verbose_name='Posición Y visual (UI)'),
        ),
    ]
