# Generated by Django 6.0.6 on 2026-07-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_ampliar_scope_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(default='🏷️', max_length=10, verbose_name='Ícono (emoji)'),
        ),
    ]
