# Generated by Django 6.0.6 on 2026-08-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_categoria_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='es_contenedor',
            field=models.BooleanField(default=False, help_text='Si está marcado, esta categoría puede contener subcategorías.', verbose_name='Es contenedor'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='inventario.categoria', verbose_name='Categoría padre'),
        ),
    ]
