# Generated by Django 6.0.6 on 2026-08-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_categoria_es_contenedor_categoria_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='meli_category_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Categoría Mercado Libre'),
        ),
    ]
