# Generated by Django 6.0.6 on 2026-09-25 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_contenedor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='dueno_externo_nombre',
            field=models.CharField(blank=True, help_text='Nombre plano de un dueño que NO es usuario de la plataforma. Convive con la FK dueno_original: alcanza uno de los dos para que el objeto tenga dueño.', max_length=200, verbose_name='Dueño original externo (sin cuenta)'),
        ),
        migrations.CreateModel(
            name='DecisionVotacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('dueno_sin_beneficiario', 'Dueño original definido sin beneficiario')], default='dueno_sin_beneficiario', max_length=40, verbose_name='Motivo de la votación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('resultado', models.JSONField(blank=True, default=dict, help_text='Resumen de la decisión: opción ganadora, conteos y beneficiario asignado.', verbose_name='Resultado')),
                ('resuelta_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('estok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='inventario.estok', verbose_name='Estok (tenant) que vota')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='inventario.objeto', verbose_name='Objeto en disputa')),
            ],
            options={
                'verbose_name': 'Votación de decisión',
                'verbose_name_plural': 'Votaciones de decisión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotoDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opcion', models.CharField(choices=[('asignar_beneficiario', 'Asignar beneficiario'), ('vender', 'Vender'), ('conservar', 'Conservar'), ('tirar', 'Tirar / Desechar')], max_length=30, verbose_name='Opción elegida')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del voto')),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos_como_beneficiario', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiario propuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_decision', to=settings.AUTH_USER_MODEL, verbose_name='Votante')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='inventario.decisionvotacion', verbose_name='Votación')),
            ],
            options={
                'verbose_name': 'Voto de decisión',
                'verbose_name_plural': 'Votos de decisión',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='decisionvotacion',
            index=models.Index(fields=['estado', 'estok'], name='inventario__estado_5fb7db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votodecision',
            unique_together={('votacion', 'usuario')},
        ),
    ]
