# Generated by Django 6.0.6 on 2026-08-21 16:12
# Edited manually para evitar pérdida de datos: la copia de las subclases
# multi-tabla hacia Objeto se ejecuta ANTES de los RemoveField/DeleteModel.

from django.db import migrations, models


def copiar_datos_subclases_a_objeto(apps, schema_editor):
    """Copia los datos de las tablas hijas multi-tabla a los campos de Objeto.

    Se ejecuta DESPUÉS de los AddField (para que los campos destino existan)
    y ANTES de los RemoveField/DeleteModel (para poder leer objeto_ptr_id).
    Taxonomía unificada: 1 Objeto = 1 Categoría, sin subclases.
    """
    Objeto = apps.get_model('inventario', 'Objeto')
    LibroRevista = apps.get_model('inventario', 'LibroRevista')
    MuebleArte = apps.get_model('inventario', 'MuebleArte')
    Ropa = apps.get_model('inventario', 'Ropa')
    Tecnologia = apps.get_model('inventario', 'Tecnologia')

    def _no_vacio(value):
        return value not in (None, '', [], {}, ())

    def _aplicar(pk, campos):
        if not pk or not campos:
            return
        Objeto.objects.filter(pk=pk).update(**campos)

    # LibroRevista → Objeto
    for hijo in LibroRevista.objects.all().iterator():
        campos = {k: v for k, v in {
            'autor': hijo.autor,
            'edicion': hijo.edicion,
            'anio': hijo.anio,
            'isbn_issn': hijo.isbn_issn,
            'editorial': getattr(hijo, 'editorial', None),
            'idioma': getattr(hijo, 'idioma', None),
            'nombre_serie': getattr(hijo, 'nombre_serie', None),
            'numero_tomo': getattr(hijo, 'numero_tomo', None),
            'titulo_tomo': getattr(hijo, 'titulo_tomo', None),
        }.items() if _no_vacio(v)}
        _aplicar(hijo.objeto_ptr_id, campos)

    # MuebleArte → Objeto
    for hijo in MuebleArte.objects.all().iterator():
        campos = {k: v for k, v in {
            'material': hijo.material,
            'largo': hijo.largo,
            'ancho': hijo.ancho,
            'alto': hijo.alto,
            'artista_fabricante': hijo.artista_fabricante,
        }.items() if _no_vacio(v)}
        _aplicar(hijo.objeto_ptr_id, campos)

    # Ropa → Objeto
    for hijo in Ropa.objects.all().iterator():
        campos = {k: v for k, v in {
            'tamano': hijo.tamano,
        }.items() if _no_vacio(v)}
        _aplicar(hijo.objeto_ptr_id, campos)

    # Tecnologia → Objeto
    for hijo in Tecnologia.objects.all().iterator():
        campos = {k: v for k, v in {
            'marca': hijo.marca,
            'modelo': hijo.modelo,
            'numero_serie': hijo.numero_serie,
            'peso': hijo.peso,
            'especificaciones': hijo.especificaciones,
        }.items() if _no_vacio(v)}
        _aplicar(hijo.objeto_ptr_id, campos)


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_categoria_meli_category_id'),
    ]

    operations = [
        # 1) Agregar a Objeto todos los campos que antes vivían en las subclases
        migrations.AddField(
            model_name='objeto',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de publicación'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='artista_fabricante',
            field=models.CharField(blank=True, max_length=300, verbose_name='Artista / Fabricante'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='autor',
            field=models.CharField(blank=True, max_length=300, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='edicion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edición'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='editorial',
            field=models.CharField(blank=True, help_text='Ej: Planeta DeAgostini, DC Comics, Marvel', max_length=200, verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena especificaciones flexibles en formato JSON (RAM, almacenamiento, etc.)', verbose_name='Especificaciones técnicas (JSON)'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='idioma',
            field=models.CharField(blank=True, help_text='Ej: Español, Inglés, Portugués', max_length=100, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='isbn_issn',
            field=models.CharField(blank=True, help_text='Código ISBN para libros o ISSN para revistas', max_length=30, verbose_name='ISBN / ISSN'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largo (cm)'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='marca',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='material',
            field=models.CharField(blank=True, max_length=200, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='nombre_serie',
            field=models.CharField(blank=True, help_text='Ej: Garfield, Batman, Los Simpsons', max_length=300, verbose_name='Nombre de la serie'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie único del dispositivo', max_length=200, verbose_name='Número de serie'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='numero_tomo',
            field=models.IntegerField(blank=True, help_text='Ej: 2, 15, 100', null=True, verbose_name='Número del tomo'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='tamano',
            field=models.CharField(blank=True, help_text='Ej: S, M, L, XL, 38, 42, etc.', max_length=50, verbose_name='Tamaño / Talla'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='titulo_tomo',
            field=models.CharField(blank=True, help_text='Ej: Se queda con la torta, El caballero oscuro', max_length=300, verbose_name='Título del tomo'),
        ),
        # 2) Copiar los datos de las subclases a Objeto ANTES de eliminar las tablas
        migrations.RunPython(
            copiar_datos_subclases_a_objeto,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3) Quitar el parent link (objeto_ptr) de las hijas multi-tabla
        migrations.RemoveField(
            model_name='mueblearte',
            name='objeto_ptr',
        ),
        migrations.RemoveField(
            model_name='ropa',
            name='objeto_ptr',
        ),
        migrations.RemoveField(
            model_name='tecnologia',
            name='objeto_ptr',
        ),
        # 4) Eliminar los modelos multi-tabla (los datos ya están en Objeto)
        migrations.DeleteModel(
            name='LibroRevista',
        ),
        migrations.DeleteModel(
            name='MuebleArte',
        ),
        migrations.DeleteModel(
            name='Ropa',
        ),
        migrations.DeleteModel(
            name='Tecnologia',
        ),
    ]
