# Generated by Django 6.0.6 on 2026-09-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# ---------------------------------------------------------------------------
# ROL "ADMINISTRADOR FÍSICO" (Encargado de Almacén / Gestor del espacio físico)
# ---------------------------------------------------------------------------
# Se crea acá (y no solo en seed_data) para que las bases YA existentes en
# producción reciban el rol al aplicar la migración, sin depender de que se
# vuelva a correr el seeding. El flag `es_administrador_fisico` es lo que
# habilita confirmar el descarte final y despachar envíos vendidos
# (inventario/services/descarte_service.py).

ROLE_ADMIN_FISICO = 'Administrador Físico'

ROLE_ADMIN_FISICO_DEFAULTS = {
    'description': (
        'Encargado de Almacén / Gestor del espacio físico: además de editar, es '
        'el único rol que puede confirmar el descarte final de objetos y '
        'despachar los envíos vendidos.'
    ),
    'can_read': True,
    'can_write': True,
    'can_edit': True,
    'can_delete': False,
    'es_administrador_fisico': True,
}


def crear_rol_administrador_fisico(apps, schema_editor):
    """Crea el rol Administrador Físico si todavía no existe (idempotente)."""
    Role = apps.get_model('inventario', 'Role')
    Role.objects.get_or_create(
        name=ROLE_ADMIN_FISICO,
        defaults=ROLE_ADMIN_FISICO_DEFAULTS,
    )


def eliminar_rol_administrador_fisico(apps, schema_editor):
    """Revierte la creación del rol (las membresías quedan con role=None)."""
    Role = apps.get_model('inventario', 'Role')
    Role.objects.filter(name=ROLE_ADMIN_FISICO).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_objeto_dueno_externo_nombre_decisionvotacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='descartado_en',
            field=models.DateTimeField(blank=True, help_text='Momento exacto en que se ordenó tirar el objeto (inicio del período de gracia).', null=True, verbose_name='Orden de descarte emitida'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='despachado_en',
            field=models.DateTimeField(blank=True, help_text='Momento en que el Administrador Físico despachó el envío del objeto vendido.', null=True, verbose_name='Envío despachado'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='despachado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_despachados', to=settings.AUTH_USER_MODEL, verbose_name='Despachado por'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='fecha_limite_descarte',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora EXACTA en que vence el período de gracia del descarte. Mientras no venza, el objeto sigue visible y puede ser reclamado.', null=True, verbose_name='Fin del período de gracia'),
        ),
        migrations.AddField(
            model_name='role',
            name='es_administrador_fisico',
            field=models.BooleanField(default=False, help_text='Encargado de Almacén / Gestor del espacio físico. Solo este rol (o un superusuario) puede confirmar el descarte final y despachar envíos.', verbose_name='Administrador Físico (almacén)'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='owner_action',
            field=models.CharField(blank=True, choices=[('vender', 'Vender'), ('conservar', 'Conservar'), ('tirar', 'Tirar / Desechar'), ('mudar', 'Mudar / Reclamar para mudanza')], help_text='Decisión del dueño original sobre qué hacer con el objeto: Vender, Conservar o Tirar', max_length=20, null=True, verbose_name='Acción del dueño original'),
        ),
        migrations.RunPython(
            crear_rol_administrador_fisico,
            eliminar_rol_administrador_fisico,
        ),
    ]
