# Generated by Django 6.0.6 on 2026-10-06 12:00
#
# «ESPACIO ÚNICO» (bloque monolítico declarado): campo nuevo en Ubicacion
# (Habitación/Espacio) y en Contenedor (Caja/Espacio/Mueble). El serializer de
# Contenedor activa el flag por defecto al crear una CAJA (regla de negocio).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_taxonomia_cinco_tipos_y_transito_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='espacio_unico',
            field=models.BooleanField(default=False, help_text='Marca el contenedor (Caja/Espacio/Mueble) como un bloque monolítico sin subdivisiones internas: queda listo para recibir objetos de forma directa, sin quedar «En Tránsito Interno». Las Cajas nacen con este flag activado por defecto; destildalo para dividirlas.', verbose_name='Espacio único (monolítico)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='espacio_unico',
            field=models.BooleanField(default=False, help_text='Marca la habitación/espacio como un bloque monolítico sin subdivisiones internas: queda listo para recibir objetos de forma directa, sin quedar «En Tránsito».', verbose_name='Espacio único (monolítico)'),
        ),
    ]
