"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

Configuración preparada para Coolify con variables de entorno.
Soporta PostgreSQL 17, JWT, CORS dinámico, IA híbrida y herencia multi-tabla.
"""

import os
from pathlib import Path
from datetime import timedelta

import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# SEGURIDAD - Variables de Entorno
# =============================================================================
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-g4r3kqe=*am$y!rk@63wj3)ctpw28ui-4zrg)419q0ky=9*9+9'
)

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')
# Compatibilidad con variable anterior
if not os.environ.get('DEBUG'):
    DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    '127.0.0.1,localhost,eeestok.duckdns.org,sq641axhkdx4oz4oss522ht9.178.156.224.212.sslip.io'
).split(',')

# =============================================================================
# CSRF TRUSTED ORIGINS (para /admin y formularios POST)
# =============================================================================
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://eeestok.duckdns.org,https://sq641axhkdx4oz4oss522ht9.178.156.224.212.sslip.io'
).split(',')

# =============================================================================
# CORS CONFIGURATION
# En producción (Coolify/Hetzner) se permite todo origen para que Astro
# (servido por Nginx en otro contenedor/dominio) pueda comunicarse con la API.
# En desarrollo se restringe a los orígenes locales.
# =============================================================================
CORS_ALLOW_ALL_ORIGINS = os.environ.get(
    'CORS_ALLOW_ALL_ORIGINS', 'True'
).lower() in ('true', '1', 'yes')

CORS_ALLOWED_ORIGINS = os.environ.get(
    'DJANGO_CORS_ORIGINS',
    'http://localhost:4321,http://localhost:4322,http://127.0.0.1:4321,http://127.0.0.1:4322'
).split(',')

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'origin',
    'x-csrftoken',
    'x-requested-with',
]

# =============================================================================
# APPS
# =============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# =============================================================================
# DATABASE - PostgreSQL 17 (Coolify Resource)
# Soporta DATABASE_URL (formato: postgres://user:pass@host:port/dbname)
# y también variables individuales DB_* para compatibilidad.
# =============================================================================
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('DB_NAME', 'estok_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'C05m05.'),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

# =============================================================================
# CUSTOM USER MODEL
# =============================================================================
AUTH_USER_MODEL = 'inventario.CustomUser'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# REST FRAMEWORK + JWT
# =============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        seconds=int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME', '3600'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        seconds=int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME', '604800'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_USER_CLASSES': ('rest_framework_simplejwt.models.TokenUser',),
}

# =============================================================================
# LOCALIZATION
# =============================================================================
LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# =============================================================================
# STATIC & MEDIA FILES
# =============================================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise: servir archivos estáticos en producción sin necesidad de Nginx
WHITENOISE_AUTOREFRESH = False
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media'))

# =============================================================================
# IA HÍBRIDA - Configuración para LM Studio (RX 9060 XT local)
# =============================================================================
AI_API_ENDPOINT = os.environ.get(
    'AI_API_ENDPOINT',
    'http://localhost:1234/v1'
)
AI_API_TIMEOUT = int(os.environ.get('AI_API_TIMEOUT', '180'))
AI_HIGH_RES_TIMEOUT = int(os.environ.get('AI_HIGH_RES_TIMEOUT', '240'))
